name: Deploy AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/${{ secrets.SERVER_USER }}/fastapi-filescan

        git fetch --all
        git checkout main
        git pull origin main

        docker stop fastapi-filescan || true
        docker rm fastapi-filescan || true
        docker rmi fastapi-filescan || true
        docker build -t fastapi-filescan .
        docker run -d --name fastapi-filescan -p 8000:8000 fastapi-filescan
        docker image prune -f
        EOF
